services:
  - type: static_site
    name: frontend-employee
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://employee-referral-system.onrender.com/api
